[package]
name        = "session_log"
version     = "0.4.1"
edition     = "2021"
license     = "MIT"
repository  = "https://githib.com/tnthung/session_log"
description = "A simple session log library for Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tap     = "1.0.1"
chrono  = "0.4.44"
log     = { version = "0.4.29", features = ["kv"]}
colored = { version = "3.1.1", optional = true }
uuid = { version = "1.23.1", features = ["v7"] }

[features]
color = ["dep:colored"]
style = []
batch = []
