[package]
name        = "session_log"
version     = "0.4.1"
edition     = "2021"
license     = "MIT"
repository  = "https://githib.com/tnthung/session_log"
description = "A simple session log library for Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log     = "0.4.29"
tap     = "1.0.1"
chrono  = "0.4.44"
colored = { version = "3.1.1", optional = true }

[features]
color = ["dep:colored"]
batch = []
