[package]
name = "session_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid      = "1.8.0"
chrono    = "0.4.38"
once_cell = "1.19.0"
